FROM node:16-alpine

WORKDIR /react-docker-example/

COPY public/ /react-docker-example/public
COPY src/ /react-docker-example/src
COPY package.json /react-docker-example/

# Install dependencies
RUN npm install --legacy-peer-deps

CMD ["npm", "start"]

